using Ecs.Action.Systems;
using Ecs.Action.Systems.Shoot;
using Ecs.Core;
using Ecs.Game.Systems;
using Ecs.Game.Systems.Bullet;
using Ecs.Game.Systems.Camera;
using Ecs.Game.Systems.Initialize;
using Ecs.Game.Systems.Player;
using Ecs.Scheduler.Systems;
using Ecs.Signal.Systems;
using Ecs.Utils;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.InstallerGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ecs.Installers {
	public static class GameEcsSystems {
		public static void Install(DiContainer container, bool isDebug = true){
			Urgent(container, isDebug);
			High(container, isDebug);
			Normal(container, isDebug);
			Low(container, isDebug);
		}

		private static void Urgent(DiContainer container, bool isDebug) {
 
			// Common -10000
			SystemInstallHelper.Install<UnityTimeProvider>(container);	// -10000 Common

			// Camera 0000
			SystemInstallHelper.Install<CameraBrainUpdateSystem>(container);	// 0000 Camera
		 }

		private static void High(DiContainer container, bool isDebug) {
 
			// Initialization 0010
			SystemInstallHelper.Install<GameInitializeSystem>(container);	// 0010 Initialization
			SystemInstallHelper.Install<CameraInitializeSystem>(container);	// 0020 Initialization
		 }

		private static void Normal(DiContainer container, bool isDebug) {
 
			// Initialization 0030
			SystemInstallHelper.Install<PlayerInitializeSystem>(container);	// 0030 Initialization

			// Move 0300
			SystemInstallHelper.Install<PlayerMovementSystem>(container);	// 0300 Move
			SystemInstallHelper.Install<BulletMovementSystem>(container);	// 0300 Shoot
			SystemInstallHelper.Install<ShootPlayerSpawnBulletSystem>(container);	// 0300 Shoot

			// Initialization 0700
			SystemInstallHelper.Install<InstantiateSystem>(container);	// 0700 Initialization

			// Move 0900
			SystemInstallHelper.Install<MovePlayerSystem>(container);	// 0900 Move

			// Scheduler 1970
			SystemInstallHelper.Install<ExecuteScheduledActionSystem>(container);	// 1970 Scheduler
			SystemInstallHelper.Install<IntervalAccumulatorSystem>(container);	// 1970 Scheduler
			SystemInstallHelper.Install<TimerSystem>(container);	// 1974 Scheduler
			SystemInstallHelper.Install<ElapsedSystem>(container);	// 1980 Scheduler
			SystemInstallHelper.Install<IntervalSystem>(container);	// 1984 Scheduler

			// Shoot 2000
			SystemInstallHelper.Install<ShootDestroySystem>(container);	// 2000 Shoot
		 }

		private static void Low(DiContainer container, bool isDebug) {
 
			// Initialization 2000
			SystemInstallHelper.Install<SignalStartSystem>(container);	// 2000 Initialization
		 }

	}
}