
using Zenject; 
using Ecs.Utils; 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.InstallerGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ecs.Installers {
	public static class GeneralEcsSystems {
		public static void Install(DiContainer container, bool isDebug = true){
		}

	}
}